# 지하철 역별 상권 분석

In [113]:
import pandas as pd
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

PATH='C:/Users/castl/Desktop/2022bigdata/visualize_project/data'

sp=pd.read_csv(PATH+'/서울시 우리마을가게 상권분석서비스(상권-생활인구).csv',encoding='cp949')
income_21=pd.read_csv(PATH+'/서울시 우리마을가게 상권분석서비스(상권-추정매출).csv',encoding='cp949')
where=pd.read_csv(PATH+'/서울시 우리마을가게 상권분석서비스(상권영역).csv',encoding='cp949')
gu_code=pd.read_csv(PATH+'/행정동코드_매핑정보_2018.csv')

## 생활인구

: 통신데이터로 특정 시점의 개인이 위차한 지역 인구(상주인구+직장인구)

In [102]:
sp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46263 entries, 0 to 46262
Columns: 532 entries, 기준 년코드 to 여성연령대_60_이상_일요일시간대_6_생활인구_수
dtypes: int64(529), object(3)
memory usage: 187.8+ MB

In [103]:
for i in sp.keys():
    print(i,'-->',type(sp[i][0]),sp[i][0])

기준 년코드 --> <class 'numpy.int64'> 2021
기준_분기_코드 --> <class 'numpy.int64'> 3
상권_구분_코드 --> <class 'str'> U
 상권_구분_코드_명 --> <class 'str'> 관광특구
상권_코드 --> <class 'numpy.int64'> 1001496
상권_코드_명 --> <class 'str'> 강남 마이스 관광특구
총_생활인구_수 --> <class 'numpy.int64'> 84144
남성_생활인구_수 --> <class 'numpy.int64'> 42839
여성_생활인구_수 --> <class 'numpy.int64'> 41306
연령대_10_생활인구_수 --> <class 'numpy.int64'> 5308
연령대_20_생활인구_수 --> <class 'numpy.int64'> 17883
연령대_30_생활인구_수 --> <class 'numpy.int64'> 23311
연령대_40_생활인구_수 --> <class 'numpy.int64'> 18730
연령대_50_생활인구_수 --> <class 'numpy.int64'> 10423
연령대_60_이상_생활인구_수 --> <class 'numpy.int64'> 8490
시간대_1_생활인구_수 --> <class 'numpy.int64'> 6223
시간대_2_생활인구_수 --> <class 'numpy.int64'> 17115
시간대_3_생활인구_수 --> <class 'numpy.int64'> 19093
시간대_4_생활인구_수 --> <class 'numpy.int64'> 19727
시간대_5_생활인구_수 --> <class 'numpy.int64'> 17246
시간대_6_생활인구_수 --> <class 'numpy.int64'> 4738
월요일_생활인구_수 --> <class 'numpy.int64'> 12423
화요일_생활인구_수 --> <class 'numpy.int64'> 13019
수요일_생활인구_수 --> <class 'numpy.int64'> 13178
목요일_생활인구_수 --> <class 'numpy.int64'> 13992
금요일_생활인구_수 --> <class 'numpy.int64'> 13701
토요일_생활인구_수 --> <class 'numpy.int64'> 9591
일요일_생활인구_수 --> <class 'numpy.int64'> 8244
남성연령대_10_월요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 40
남성연령대_10_월요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 52
남성연령대_10_월요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 50
남성연령대_10_월요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 57
남성연령대_10_월요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 63
남성연령대_10_월요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 28
남성연령대_10_화요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 42
남성연령대_10_화요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 49
남성연령대_10_화요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 55
남성연령대_10_화요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 60
남성연령대_10_화요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 64
남성연령대_10_화요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 27
남성연령대_10_수요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 39
남성연령대_10_수요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 48
남성연령대_10_수요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 50
남성연령대_10_수요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 60
남성연령대_10_수요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 69
남성연령대_10_수요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 30
남성연령대_10_목요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 43
남성연령대_10_목요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 50
남성연령대_10_목요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 51
남성연령대_10_목요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 59
남성연령대_10_목요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 65
남성연령대_10_목요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 31
남성연령대_10_금요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 34
남성연령대_10_금요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 51
남성연령대_10_금요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 53
남성연령대_10_금요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 62
남성연령대_10_금요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 75
남성연령대_10_금요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 31
남성연령대_10_토요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 40
남성연령대_10_토요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 61
남성연령대_10_토요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 81
남성연령대_10_토요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 91
남성연령대_10_토요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 109
남성연령대_10_토요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 36
남성연령대_10_일요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 42
남성연령대_10_일요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 57
남성연령대_10_일요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 76
남성연령대_10_일요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 97
남성연령대_10_일요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 102
남성연령대_10_일요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 31
남성연령대_20_월요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 69
남성연령대_20_월요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 201
남성연령대_20_월요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 222
남성연령대_20_월요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 234
남성연령대_20_월요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 222
남성연령대_20_월요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 59
남성연령대_20_화요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 70
남성연령대_20_화요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 204
남성연령대_20_화요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 233
남성연령대_20_화요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 244
남성연령대_20_화요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 234
남성연령대_20_화요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 58
남성연령대_20_수요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 69
남성연령대_20_수요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 208
남성연령대_20_수요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 243
남성연령대_20_수요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 256
남성연령대_20_수요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 243
남성연령대_20_수요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 60
남성연령대_20_목요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 69
남성연령대_20_목요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 223
남성연령대_20_목요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 259
남성연령대_20_목요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 272
남성연령대_20_목요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 254
남성연령대_20_목요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 63
남성연령대_20_금요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 69
남성연령대_20_금요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 223
남성연령대_20_금요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 260
남성연령대_20_금요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 270
남성연령대_20_금요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 249
남성연령대_20_금요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 64
남성연령대_20_토요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 69
남성연령대_20_토요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 122
남성연령대_20_토요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 180
남성연령대_20_토요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 238
남성연령대_20_토요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 230
남성연령대_20_토요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 61
남성연령대_20_일요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 74
남성연령대_20_일요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 108
남성연령대_20_일요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 153
남성연령대_20_일요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 201
남성연령대_20_일요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 197
남성연령대_20_일요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 49
남성연령대_30_월요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 100
남성연령대_30_월요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 421
남성연령대_30_월요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 436
남성연령대_30_월요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 434
남성연령대_30_월요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 375
남성연령대_30_월요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 102
남성연령대_30_화요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 123
남성연령대_30_화요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 434
남성연령대_30_화요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 453
남성연령대_30_화요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 457
남성연령대_30_화요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 395
남성연령대_30_화요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 102
남성연령대_30_수요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 118
남성연령대_30_수요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 430
남성연령대_30_수요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 463
남성연령대_30_수요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 463
남성연령대_30_수요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 397
남성연령대_30_수요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 105
남성연령대_30_목요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 124
남성연령대_30_목요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 461
남성연령대_30_목요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 497
남성연령대_30_목요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 494
남성연령대_30_목요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 420
남성연령대_30_목요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 113
남성연령대_30_금요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 125
남성연령대_30_금요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 446
남성연령대_30_금요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 478
남성연령대_30_금요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 464
남성연령대_30_금요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 383
남성연령대_30_금요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 105
남성연령대_30_토요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 122
남성연령대_30_토요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 185
남성연령대_30_토요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 235
남성연령대_30_토요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 271
남성연령대_30_토요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 271
남성연령대_30_토요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 88
남성연령대_30_일요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 125
남성연령대_30_일요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 162
남성연령대_30_일요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 196
남성연령대_30_일요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 228
남성연령대_30_일요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 219
남성연령대_30_일요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 69
남성연령대_40_월요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 103
남성연령대_40_월요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 428
남성연령대_40_월요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 412
남성연령대_40_월요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 401
남성연령대_40_월요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 337
남성연령대_40_월요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 98
남성연령대_40_화요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 133
남성연령대_40_화요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 446
남성연령대_40_화요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 434
남성연령대_40_화요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 425
남성연령대_40_화요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 350
남성연령대_40_화요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 102
남성연령대_40_수요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 129
남성연령대_40_수요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 436
남성연령대_40_수요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 437
남성연령대_40_수요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 427
남성연령대_40_수요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 354
남성연령대_40_수요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 101
남성연령대_40_목요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 129
남성연령대_40_목요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 468
남성연령대_40_목요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 468
남성연령대_40_목요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 459
남성연령대_40_목요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 370
남성연령대_40_목요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 108
남성연령대_40_금요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 133
남성연령대_40_금요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 452
남성연령대_40_금요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 441
남성연령대_40_금요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 421
남성연령대_40_금요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 332
남성연령대_40_금요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 101
남성연령대_40_토요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 127
남성연령대_40_토요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 188
남성연령대_40_토요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 196
남성연령대_40_토요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 203
남성연령대_40_토요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 197
남성연령대_40_토요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 76
남성연령대_40_일요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 112
남성연령대_40_일요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 152
남성연령대_40_일요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 165
남성연령대_40_일요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 173
남성연령대_40_일요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 169
남성연령대_40_일요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 67
남성연령대_50_월요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 65
남성연령대_50_월요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 236
남성연령대_50_월요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 210
남성연령대_50_월요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 206
남성연령대_50_월요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 163
남성연령대_50_월요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 55
남성연령대_50_화요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 75
남성연령대_50_화요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 240
남성연령대_50_화요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 218
남성연령대_50_화요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 214
남성연령대_50_화요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 171
남성연령대_50_화요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 55
남성연령대_50_수요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 72
남성연령대_50_수요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 244
남성연령대_50_수요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 222
남성연령대_50_수요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 216
남성연령대_50_수요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 174
남성연령대_50_수요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 59
남성연령대_50_목요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 81
남성연령대_50_목요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 256
남성연령대_50_목요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 240
남성연령대_50_목요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 233
남성연령대_50_목요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 185
남성연령대_50_목요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 59
남성연령대_50_금요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 82
남성연령대_50_금요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 254
남성연령대_50_금요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 235
남성연령대_50_금요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 221
남성연령대_50_금요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 171
남성연령대_50_금요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 60
남성연령대_50_토요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 82
남성연령대_50_토요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 128
남성연령대_50_토요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 123
남성연령대_50_토요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 118
남성연령대_50_토요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 112
남성연령대_50_토요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 45
남성연령대_50_일요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 64
남성연령대_50_일요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 101
남성연령대_50_일요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 100
남성연령대_50_일요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 101
남성연령대_50_일요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 94
남성연령대_50_일요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 40
남성연령대_60_이상_월요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 50
남성연령대_60_이상_월요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 146
남성연령대_60_이상_월요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 131
남성연령대_60_이상_월요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 125
남성연령대_60_이상_월요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 99
남성연령대_60_이상_월요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 40
남성연령대_60_이상_화요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 66
남성연령대_60_이상_화요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 149
남성연령대_60_이상_화요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 141
남성연령대_60_이상_화요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 131
남성연령대_60_이상_화요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 104
남성연령대_60_이상_화요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 40
남성연령대_60_이상_수요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 66
남성연령대_60_이상_수요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 149
남성연령대_60_이상_수요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 141
남성연령대_60_이상_수요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 131
남성연령대_60_이상_수요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 104
남성연령대_60_이상_수요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 40
남성연령대_60_이상_목요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 67
남성연령대_60_이상_목요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 156
남성연령대_60_이상_목요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 149
남성연령대_60_이상_목요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 142
남성연령대_60_이상_목요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 106
남성연령대_60_이상_목요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 42
남성연령대_60_이상_금요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 69
남성연령대_60_이상_금요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 156
남성연령대_60_이상_금요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 145
남성연령대_60_이상_금요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 136
남성연령대_60_이상_금요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 105
남성연령대_60_이상_금요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 41
남성연령대_60_이상_토요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 65
남성연령대_60_이상_토요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 105
남성연령대_60_이상_토요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 99
남성연령대_60_이상_토요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 92
남성연령대_60_이상_토요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 82
남성연령대_60_이상_토요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 36
남성연령대_60_이상_일요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 49
남성연령대_60_이상_일요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 83
남성연령대_60_이상_일요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 80
남성연령대_60_이상_일요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 78
남성연령대_60_이상_일요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 75
남성연령대_60_이상_일요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 32
여성연령대_10_월요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 39
여성연령대_10_월요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 58
여성연령대_10_월요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 76
여성연령대_10_월요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 86
여성연령대_10_월요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 90
여성연령대_10_월요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 30
여성연령대_10_화요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 41
여성연령대_10_화요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 57
여성연령대_10_화요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 69
여성연령대_10_화요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 85
여성연령대_10_화요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 91
여성연령대_10_화요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 28
여성연령대_10_수요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 41
여성연령대_10_수요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 58
여성연령대_10_수요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 75
여성연령대_10_수요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 92
여성연령대_10_수요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 92
여성연령대_10_수요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 28
여성연령대_10_목요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 41
여성연령대_10_목요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 60
여성연령대_10_목요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 74
여성연령대_10_목요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 85
여성연령대_10_목요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 86
여성연령대_10_목요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 28
여성연령대_10_금요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 41
여성연령대_10_금요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 61
여성연령대_10_금요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 81
여성연령대_10_금요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 97
여성연령대_10_금요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 107
여성연령대_10_금요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 34
여성연령대_10_토요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 41
여성연령대_10_토요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 64
여성연령대_10_토요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 111
여성연령대_10_토요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 151
여성연령대_10_토요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 147
여성연령대_10_토요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 39
여성연령대_10_일요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 39
여성연령대_10_일요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 56
여성연령대_10_일요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 106
여성연령대_10_일요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 152
여성연령대_10_일요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 141
여성연령대_10_일요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 33
여성연령대_20_월요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 77
여성연령대_20_월요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 300
여성연령대_20_월요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 362
여성연령대_20_월요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 389
여성연령대_20_월요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 354
여성연령대_20_월요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 71
여성연령대_20_화요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 77
여성연령대_20_화요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 317
여성연령대_20_화요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 381
여성연령대_20_화요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 410
여성연령대_20_화요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 369
여성연령대_20_화요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 70
여성연령대_20_수요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 69
여성연령대_20_수요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 319
여성연령대_20_수요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 395
여성연령대_20_수요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 427
여성연령대_20_수요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 376
여성연령대_20_수요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 73
여성연령대_20_목요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 70
여성연령대_20_목요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 341
여성연령대_20_목요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 426
여성연령대_20_목요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 459
여성연령대_20_목요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 403
여성연령대_20_목요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 78
여성연령대_20_금요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 75
여성연령대_20_금요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 336
여성연령대_20_금요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 419
여성연령대_20_금요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 454
여성연령대_20_금요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 409
여성연령대_20_금요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 82
여성연령대_20_토요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 83
여성연령대_20_토요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 161
여성연령대_20_토요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 274
여성연령대_20_토요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 374
여성연령대_20_토요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 356
여성연령대_20_토요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 76
여성연령대_20_일요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 93
여성연령대_20_일요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 133
여성연령대_20_일요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 217
여성연령대_20_일요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 302
여성연령대_20_일요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 286
여성연령대_20_일요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 59
여성연령대_30_월요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 83
여성연령대_30_월요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 366
여성연령대_30_월요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 415
여성연령대_30_월요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 413
여성연령대_30_월요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 337
여성연령대_30_월요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 71

여성연령대_50_목요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 33
여성연령대_50_금요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 50
여성연령대_50_금요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 145
여성연령대_50_금요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 169
여성연령대_50_금요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 166
여성연령대_50_금요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 138
여성연령대_50_금요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 36
여성연령대_50_토요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 51
여성연령대_50_토요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 108
여성연령대_50_토요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 132
여성연령대_50_토요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 136
여성연령대_50_토요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 121
여성연령대_50_토요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 31
여성연령대_50_일요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 39
여성연령대_50_일요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 89
여성연령대_50_일요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 110
여성연령대_50_일요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 118
여성연령대_50_일요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 104
여성연령대_50_일요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 28
여성연령대_60_이상_월요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 70
여성연령대_60_이상_월요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 153
여성연령대_60_이상_월요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 143
여성연령대_60_이상_월요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 127
여성연령대_60_이상_월요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 100
여성연령대_60_이상_월요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 41
여성연령대_60_이상_화요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 74
여성연령대_60_이상_화요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 159
여성연령대_60_이상_화요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 156
여성연령대_60_이상_화요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 133
여성연령대_60_이상_화요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 107
여성연령대_60_이상_화요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 41
여성연령대_60_이상_수요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 73
여성연령대_60_이상_수요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 155
여성연령대_60_이상_수요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 154
여성연령대_60_이상_수요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 140
여성연령대_60_이상_수요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 111
여성연령대_60_이상_수요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 41
여성연령대_60_이상_목요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 72
여성연령대_60_이상_목요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 163
여성연령대_60_이상_목요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 166
여성연령대_60_이상_목요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 148
여성연령대_60_이상_목요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 112
여성연령대_60_이상_목요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 44
여성연령대_60_이상_금요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 75
여성연령대_60_이상_금요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 165
여성연령대_60_이상_금요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 159
여성연령대_60_이상_금요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 146
여성연령대_60_이상_금요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 112
여성연령대_60_이상_금요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 43
여성연령대_60_이상_토요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 63
여성연령대_60_이상_토요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 110
여성연령대_60_이상_토요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 121
여성연령대_60_이상_토요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 117
여성연령대_60_이상_토요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 106
여성연령대_60_이상_토요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 38
여성연령대_60_이상_일요일시간대_1_생활인구_수 --> <class 'numpy.int64'> 62
여성연령대_60_이상_일요일시간대_2_생활인구_수 --> <class 'numpy.int64'> 96
여성연령대_60_이상_일요일시간대_3_생활인구_수 --> <class 'numpy.int64'> 107
여성연령대_60_이상_일요일시간대_4_생활인구_수 --> <class 'numpy.int64'> 109
여성연령대_60_이상_일요일시간대_5_생활인구_수 --> <class 'numpy.int64'> 99
여성연령대_60_이상_일요일시간대_6_생활인구_수 --> <class 'numpy.int64'> 39

In [104]:
for i in income_21.keys():
    print(i,'-->',type(income_21[i][0]),income_21[i][0])

기준_년_코드 --> <class 'numpy.int64'> 2021
기준_분기_코드 --> <class 'numpy.int64'> 3
상권_구분_코드 --> <class 'str'> U
상권_구분_코드_명 --> <class 'str'> 관광특구
상권_코드 --> <class 'numpy.int64'> 1001496
상권_코드_명 --> <class 'str'> 강남 마이스 관광특구
서비스_업종_코드 --> <class 'str'> CS300043
서비스_업종_코드_명 --> <class 'str'> 전자상거래업
분기당_매출_금액 --> <class 'numpy.int64'> 1713936
분기당_매출_건수 --> <class 'numpy.int64'> 34
주중_매출_비율 --> <class 'numpy.int64'> 100
주말_매출_비율 --> <class 'numpy.int64'> 0
월요일_매출_비율 --> <class 'numpy.int64'> 0
화요일_매출_비율 --> <class 'numpy.int64'> 0
수요일_매출_비율 --> <class 'numpy.int64'> 11
목요일_매출_비율 --> <class 'numpy.int64'> 89
금요일_매출_비율 --> <class 'numpy.int64'> 0
토요일_매출_비율 --> <class 'numpy.int64'> 0
일요일_매출_비율 --> <class 'numpy.int64'> 0
시간대_00~06_매출_비율 --> <class 'numpy.int64'> 0
시간대_06~11_매출_비율 --> <class 'numpy.int64'> 9
시간대_11~14_매출_비율 --> <class 'numpy.int64'> 7
시간대_14~17_매출_비율 --> <class 'numpy.int64'> 83
시간대_17~21_매출_비율 --> <class 'numpy.int64'> 2
시간대_21~24_매출_비율 --> <class 'numpy.int64'> 0
남성_매출_비율 --> <class 'numpy.int64'> 15
여성_매출_비율 --> <class 'numpy.int64'> 85
연령대_10_매출_비율 --> <class 'numpy.int64'> 0
연령대_20_매출_비율 --> <class 'numpy.int64'> 0
연령대_30_매출_비율 --> <class 'numpy.int64'> 73
연령대_40_매출_비율 --> <class 'numpy.int64'> 27
연령대_50_매출_비율 --> <class 'numpy.int64'> 0
연령대_60_이상_매출_비율 --> <class 'numpy.int64'> 0
주중_매출_금액 --> <class 'numpy.int64'> 1713936
주말_매출_금액 --> <class 'numpy.int64'> 0
월요일_매출_금액 --> <class 'numpy.int64'> 0
화요일_매출_금액 --> <class 'numpy.int64'> 0
수요일_매출_금액 --> <class 'numpy.int64'> 193352
목요일_매출_금액 --> <class 'numpy.int64'> 1520584
금요일_매출_금액 --> <class 'numpy.int64'> 0
토요일_매출_금액 --> <class 'numpy.int64'> 0
일요일_매출_금액 --> <class 'numpy.int64'> 0
시간대_00~06_매출_금액 --> <class 'numpy.int64'> 0
시간대_06~11_매출_금액 --> <class 'numpy.int64'> 148172
시간대_11~14_매출_금액 --> <class 'numpy.int64'> 116594
시간대_14~17_매출_금액 --> <class 'numpy.int64'> 1417592
시간대_17~21_매출_금액 --> <class 'numpy.int64'> 31578
시간대_21~24_매출_금액 --> <class 'numpy.int64'> 0
남성_매출_금액 --> <class 'numpy.int64'> 264766
여성_매출_금액 --> <class 'numpy.int64'> 1449170
연령대_10_매출_금액 --> <class 'numpy.int64'> 0
연령대_20_매출_금액 --> <class 'numpy.int64'> 0
연령대_30_매출_금액 --> <class 'numpy.int64'> 1255818
연령대_40_매출_금액 --> <class 'numpy.int64'> 458118
연령대_50_매출_금액 --> <class 'numpy.int64'> 0
연령대_60_이상_매출_금액 --> <class 'numpy.int64'> 0
주중_매출_건수 --> <class 'numpy.int64'> 34
주말_매출_건수 --> <class 'numpy.int64'> 0
월요일_매출_건수 --> <class 'numpy.int64'> 0
화요일_매출_건수 --> <class 'numpy.int64'> 0
수요일_매출_건수 --> <class 'numpy.int64'> 5
목요일_매출_건수 --> <class 'numpy.int64'> 29
금요일_매출_건수 --> <class 'numpy.int64'> 0
토요일_매출_건수 --> <class 'numpy.int64'> 0
일요일_매출_건수 --> <class 'numpy.int64'> 0
시간대_건수~06_매출_건수 --> <class 'numpy.int64'> 0
시간대_건수~11_매출_건수 --> <class 'numpy.int64'> 5
시간대_건수~14_매출_건수 --> <class 'numpy.int64'> 5
시간대_건수~17_매출_건수 --> <class 'numpy.int64'> 19
시간대_건수~21_매출_건수 --> <class 'numpy.int64'> 5
시간대_건수~24_매출_건수 --> <class 'numpy.int64'> 0
남성_매출_건수 --> <class 'numpy.int64'> 10
여성_매출_건수 --> <class 'numpy.int64'> 24
연령대_10_매출_건수 --> <class 'numpy.int64'> 0
연령대_20_매출_건수 --> <class 'numpy.int64'> 0
연령대_30_매출_건수 --> <class 'numpy.int64'> 19
연령대_40_매출_건수 --> <class 'numpy.int64'> 15
연령대_50_매출_건수 --> <class 'numpy.int64'> 0
연령대_60_이상_매출_건수 --> <class 'numpy.int64'> 0
점포수 --> <class 'numpy.int64'> 8

In [105]:
where=where.drop(['형태정보'],axis=1)
where

,기준_년월_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,엑스좌표_값,와이좌표_값,시군구_코드,행정동_코드
0,201810,A,골목상권,1000275,보문로26길,201886,454183,11290,11290600
1,201810,A,골목상권,1000276,보문로31길,201385,454290,11290,11290555
2,201810,D,발달상권,1001045,동작구 총신대입구역_1,198304,442948,11590,11590630
3,201810,D,발달상권,1001046,서울 관악구 신림역_4,193828,443001,11620,11620695
4,201810,D,발달상권,1001047,뱅뱅사거리_1,202960,443242,11680,11680655
...,...,...,...,...,...,...,...,...,...
1491,201810,D,발달상권,1001153,당산역_1,191112,448327,11560,11560620
1492,201810,D,발달상권,1001154,용산 전자상가_4,196450,448406,11170,11170560
1493,201810,D,발달상권,1001155,용산 전자상가_5,196870,448350,11170,11170560
1494,201810,D,발달상권,1001156,서울 강동구 길동역,212214,448512,11740,11740685
1495,201810,D,발달상권,1001120,도산공원사거리_1,202754,446796,11680,11680545

In [106]:
# 시군구 코드로 where  inner join
# 기준이 되는 colum 이름을 동일하게 하여 merge 할 수 있게함

gu_code.rename(columns={'RESD_CD':'시군구_코드','RESC_CT_NM':'시군구_명'},inplace=True)
guwhere=where.merge(gu_code[['시군구_코드','시군구_명']], how='inner', on =['시군구_코드'])
guwhere

,기준_년월_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,엑스좌표_값,와이좌표_값,시군구_코드,행정동_코드,시군구_명
0,201810,A,골목상권,1000275,보문로26길,201886,454183,11290,11290600,성북구
1,201810,A,골목상권,1000276,보문로31길,201385,454290,11290,11290555,성북구
2,201810,R,전통시장,1001338,돈암제일시장,201402,454703,11290,11290555,성북구
3,201810,A,골목상권,1000298,정릉로27길,201136,456377,11290,11290630,성북구
4,201810,A,골목상권,1000299,정릉로8길,199817,456396,11290,11290640,성북구
...,...,...,...,...,...,...,...,...,...,...
1491,201810,R,전통시장,1001404,신정제일시장,187123,446835,11470,11470620,양천구
1492,201810,R,전통시장,1001405,신정2동골목시장,189085,446859,11470,11470630,양천구
1493,201810,R,전통시장,1001406,신정3동골목시장,187005,446592,11470,11470640,양천구
1494,201810,R,전통시장,1001394,목2동시장,188801,449649,11470,11470520,양천구
1495,201810,R,전통시장,1001395,목3동시장,188065,449908,11470,11470530,양천구

In [116]:
# sp데이터 중 원하는 컬럼만 사용(요일 까지만)
want=sp.columns.unique()[:28]
sp_all=sp[want]


# 구, x좌표, y좌표 join한 생활인구 데이터
sp_all=sp_all.merge(guwhere[['상권_코드','시군구_명','엑스좌표_값','와이좌표_값']],how='inner',on='상권_코드')
sp_all

,기준 년코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,총_생활인구_수,남성_생활인구_수,여성_생활인구_수,연령대_10_생활인구_수,...,월요일_생활인구_수,화요일_생활인구_수,수요일_생활인구_수,목요일_생활인구_수,금요일_생활인구_수,토요일_생활인구_수,일요일_생활인구_수,시군구_명,엑스좌표_값,와이좌표_값
0,2021,3,U,관광특구,1001496,강남 마이스 관광특구,84144,42839,41306,5308,...,12423,13019,13178,13992,13701,9591,8244,강남구,205310,445727
1,2021,2,U,관광특구,1001496,강남 마이스 관광특구,95914,47931,47982,5297,...,14551,15070,14804,15586,15381,11155,9367,강남구,205310,445727
2,2021,1,U,관광특구,1001496,강남 마이스 관광특구,88025,44225,43800,5063,...,13456,14127,14243,14019,13307,10139,8735,강남구,205310,445727
3,2020,4,U,관광특구,1001496,강남 마이스 관광특구,90836,46313,44523,4351,...,14166,14782,15082,14512,13934,10092,8270,강남구,205310,445727
4,2020,3,U,관광특구,1001496,강남 마이스 관광특구,97662,49322,48340,5557,...,14696,15628,15297,16139,16028,10950,8926,강남구,205310,445727
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46258,2015,1,A,골목상권,1000001,계동길,107573,64734,42835,2003,...,20597,20798,18108,17141,15259,8856,6814,종로구,198799,453610
46259,2014,4,A,골목상권,1000001,계동길,135676,77984,57692,3671,...,21515,23229,23752,22540,22639,13415,8590,종로구,198799,453610
46260,2014,3,A,골목상권,1000001,계동길,166128,94632,71495,5416,...,27000,28175,23699,29227,29796,17843,10387,종로구,198799,453610
46261,2014,2,A,골목상권,1000001,계동길,164593,93204,71387,5989,...,24156,29252,29493,27228,27840,16325,10296,종로구,198799,453610
46262,2014,1,A,골목상권,1000001,계동길,147154,85726,61430,3250,...,22840,23238,25726,25684,27164,14227,8275,종로구,198799,453610

In [118]:
# null값 확인

sp_all.isna().sum()

기준 년코드              0
기준_분기_코드            0
상권_구분_코드            0
 상권_구분_코드_명         0
상권_코드               0
상권_코드_명             0
총_생활인구_수            0
남성_생활인구_수           0
여성_생활인구_수           0
연령대_10_생활인구_수       0
연령대_20_생활인구_수       0
연령대_30_생활인구_수       0
연령대_40_생활인구_수       0
연령대_50_생활인구_수       0
연령대_60_이상_생활인구_수    0
시간대_1_생활인구_수        0
시간대_2_생활인구_수        0
시간대_3_생활인구_수        0
시간대_4_생활인구_수        0
시간대_5_생활인구_수        0
시간대_6_생활인구_수        0
월요일_생활인구_수          0
화요일_생활인구_수          0
수요일_생활인구_수          0
목요일_생활인구_수          0
금요일_생활인구_수          0
토요일_생활인구_수          0
일요일_생활인구_수          0
시군구_명               0
엑스좌표_값              0
와이좌표_값              0
dtype: int64

In [122]:
#기준 년코드 2018년도 이상인 것만 사용

sp_all=sp_all[sp_all['기준 년코드']>=2018]

# sp_recent(최근 1년)
sp_recent=sp_all[((sp_all['기준 년코드']==2020)&(sp_all['기준_분기_코드']==4))|(sp_all['기준 년코드']==2021)]
sp_recent

,기준 년코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,총_생활인구_수,남성_생활인구_수,여성_생활인구_수,연령대_10_생활인구_수,...,월요일_생활인구_수,화요일_생활인구_수,수요일_생활인구_수,목요일_생활인구_수,금요일_생활인구_수,토요일_생활인구_수,일요일_생활인구_수,시군구_명,엑스좌표_값,와이좌표_값
0,2021,3,U,관광특구,1001496,강남 마이스 관광특구,84144,42839,41306,5308,...,12423,13019,13178,13992,13701,9591,8244,강남구,205310,445727
1,2021,2,U,관광특구,1001496,강남 마이스 관광특구,95914,47931,47982,5297,...,14551,15070,14804,15586,15381,11155,9367,강남구,205310,445727
2,2021,1,U,관광특구,1001496,강남 마이스 관광특구,88025,44225,43800,5063,...,13456,14127,14243,14019,13307,10139,8735,강남구,205310,445727
3,2020,4,U,관광특구,1001496,강남 마이스 관광특구,90836,46313,44523,4351,...,14166,14782,15082,14512,13934,10092,8270,강남구,205310,445727
31,2021,3,U,관광특구,1001495,잠실 관광특구,3029714,1470103,1559610,280084,...,426509,430062,440535,443585,447048,433886,408089,송파구,210191,446339
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46204,2020,4,A,골목상권,1000002,난계로27길,354032,180395,173637,17245,...,50540,51172,50881,49644,50213,50592,50991,종로구,201996,452630
46232,2021,3,A,골목상권,1000001,계동길,275537,138891,136646,37211,...,40377,42040,42218,43722,41892,33838,31450,종로구,198799,453610
46233,2021,2,A,골목상권,1000001,계동길,302793,153690,149104,46682,...,45907,47023,45752,47205,46503,36648,33759,종로구,198799,453610
46234,2021,1,A,골목상권,1000001,계동길,282796,142207,140590,34007,...,42432,44311,43579,43185,41685,34576,33028,종로구,198799,453610
46235,2020,4,A,골목상권,1000001,계동길,300188,151713,148474,37781,...,46328,47520,47456,45328,43833,36329,33394,종로구,198799,453610